name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install terraform
      run: | 
          sudo curl -L https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip -o /tmp/terraform_linux_amd64.zip
          sudo unzip /tmp/terraform_linux_amd64.zip -d /usr/bin
          sudo rm -f /tmp/terraform_linux_amd64.zip
    - name: Apply in AWS
      env:
        TF_VAR_aws_access_key: ${{ secrets.TF_VAR_aws_access_key }}
        TF_VAR_aws_secret_key: ${{ secrets.TF_VAR_aws_secret_key }}
        TF_VAR_dockeree_license_url: ${{ secrets.TF_VAR_dockeree_license_url }}
      run: |
          terraform init
          export TF_VAR_aws_access_key
          export TF_VAR_aws_secret_key
          terraform validate
          export TF_VAR_dockeree_license_url
          echo '${{ secrets.dockeree_license_key }}' > docker_subscription.lic
          ssh-keygen -f id_rsa -t rsa -N ''
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          mv id_rsa ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          mv id_rsa.pub ~/.ssh
          chmod 600 ~/.ssh/id_rsa.pub
          terraform apply --auto-approve
          terraform destroy --auto-approve
    - name: Destroy in AWS on failure
      if: failure()
      env:
        TF_VAR_aws_access_key: ${{ secrets.TF_VAR_aws_access_key }}
        TF_VAR_aws_secret_key: ${{ secrets.TF_VAR_aws_secret_key }}
        TF_VAR_dockeree_license_url: ${{ secrets.TF_VAR_dockeree_license_url }}
      run: terraform destroy --auto-approve
